// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtqT8ey1nRobswsfg0lt6QxU9s8TZJSps',
    appId: '1:61236209576:web:fb7af8ae051b23871edf9d',
    messagingSenderId: '61236209576',
    projectId: 'fire-9bccc',
    authDomain: 'fire-9bccc.firebaseapp.com',
    storageBucket: 'fire-9bccc.firebasestorage.app',
    measurementId: 'G-JSXBLKVLM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD9NFERgr95llPN3hAj1W6OU1ZW-Rk3j8',
    appId: '1:61236209576:android:66ab699a2ac968391edf9d',
    messagingSenderId: '61236209576',
    projectId: 'fire-9bccc',
    storageBucket: 'fire-9bccc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc919EfGYX4LhxRTaqhCm7rX2oegjznN0',
    appId: '1:61236209576:ios:6460f7fb38739a751edf9d',
    messagingSenderId: '61236209576',
    projectId: 'fire-9bccc',
    storageBucket: 'fire-9bccc.firebasestorage.app',
    iosBundleId: 'com.example.vakansiya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc919EfGYX4LhxRTaqhCm7rX2oegjznN0',
    appId: '1:61236209576:ios:6460f7fb38739a751edf9d',
    messagingSenderId: '61236209576',
    projectId: 'fire-9bccc',
    storageBucket: 'fire-9bccc.firebasestorage.app',
    iosBundleId: 'com.example.vakansiya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtqT8ey1nRobswsfg0lt6QxU9s8TZJSps',
    appId: '1:61236209576:web:d4686949722d5bf11edf9d',
    messagingSenderId: '61236209576',
    projectId: 'fire-9bccc',
    authDomain: 'fire-9bccc.firebaseapp.com',
    storageBucket: 'fire-9bccc.firebasestorage.app',
    measurementId: 'G-EMC20LW0XC',
  );
}
